variable "hcloud_token" {
  description = "Hetzner Cloud API token (create at console.hetzner.cloud > Security > API Tokens)."
  type        = string
  sensitive   = true
}

variable "server_name" {
  description = "Name of the CX23 server."
  type        = string
  default     = "korp-cx23"
}

variable "location" {
  description = "Hetzner Cloud datacenter location."
  type        = string
  default     = "fsn1"
}

variable "image" {
  description = "OS image for the server."
  type        = string
  default     = "ubuntu-24.04"
}

variable "ssh_public_key_path" {
  description = "Optional path to the public SSH key. Defaults to keys/.hetzner.key.pub (generated by scripts/create-keys.sh)."
  type        = string
  default     = null
}

variable "ssh_key_name" {
  description = "Name of the SSH key resource registered in Hetzner Cloud."
  type        = string
  default     = "korp-deploy"
}

variable "labels" {
  description = "Labels attached to the server."
  type        = map(string)
  default = {
    project   = "korp-desafio"
    component = "app"
  }
}
